//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppEcartDemo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class category
    {
        public int categoryid { get; set; }
        public string categorycode { get; set; }
        public string caregoryname { get; set; }
    }
}
